### ISSUE TITLE
“No module named 'torchcrf' ” under linux system

### ISSUE THREAD

**Issue by AndyChinghaha** [kmkurn/pytorch-crf#111]
Hi, my code is alright runing under windows pycharm, but meet this problem under linux,my  linux env has install torchcrf with "pip install pytorchcrf",this  comes out while deployting.

I check this with "pip show TorchCRF /torchcrf"  and get 'Package(s) not found'.Then command line "pip list " to show that "pytorch-crf  0.7.2" , but "import pythorch-crf" which is a 'SyntaxError: invalid syntax' coming  with '-'  won't be ok.

**Comment by AndyChinghaha** [comment]
it seems a problem of packages managing,  I saw the folder name as torchcrf under site-packages.

**Comment by kmkurn** [comment]
Hi, yes you should import using `from torchcrf import CRF` as instructed on the docs.
