### ISSUE TITLE
Github workflow fails for python 3.6

### ISSUE THREAD

**Issue by leejuyuu** [kmkurn/pytorch-crf#117]
This is found in #116 and was also present in #113. Because the ubuntu-latest image was updated to 22.04, which does not have any installable python 3.6 tarballs, the setup-python will fail with an error message `Error: Version 3.6 with arch x64 not found`. This is because python 3.6 reached EOL in 2021. See https://github.com/actions/setup-python/issues/544 for more details.  

We have two options to make CI work again:
1. Test against the oldest supported (3.8) and the newest stable (3.12) releases. (See https://devguide.python.org/versions/)
2. Pin the ubuntu test image version to 20.04.

I would suggest option 1 so people can update to the supported python versions.

**Comment by kmkurn** [comment]
Thank you for tracking down this issue and providing references and potential solutions. I really appreciate it! I agree that option 1 seems best. Would you be interested in creating a PR for that? I think ideally the PR should be merged before #116.

**Comment by leejuyuu** [comment]
Sure! I'm trying different version combinations. The minimum available torch for python is 1.4.

Is there a reason to pin pytest and pytest-cov in the requirements? Pytest 3.2.5 gives some ModuleNotFound on python 3.12, so I would probably change that.
