### ISSUE TITLE
some thing wrong

### ISSUE THREAD

**Issue by Wangpeiyi9979** [kmkurn/pytorch-crf#32]
Hi, It is a nice job, but I meet a problem. I follow the [guide](https://pytorch-crf.readthedocs.io/en/stable/)， But something wrong:
![image](https://user-images.githubusercontent.com/42565075/55218929-74a60c80-523e-11e9-87bd-bdd11f6e24d6.png)
could you help me, thanks

pytorch : 1.0.0
python:  3.6

**Comment by kmkurn** [comment]
Could you give a minimal example code to reproduce the error?

**Comment by kmkurn** [comment]
Hi, is there an update on this?
