### ISSUE TITLE
RuntimeError: tensors used as indices must be long or byte tensors

### ISSUE THREAD

**Issue by xiaozhi0689** [kmkurn/pytorch-crf#38]
I just follow the example in the document, but I got this error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torchcrf/__init__.py", line 102, in forward
    numerator = self._compute_score(emissions, tags, mask)
  File "/opt/conda/lib/python3.6/site-packages/torchcrf/__init__.py", line 187, in _compute_score
    score += emissions[0, torch.arange(batch_size), tags[0]]
RuntimeError: tensors used as indices must be long or byte tensors`

code:

>>> import torch 
>>> from torchcrf import CRF
>>> num_tags = 5
>>> model = CRF(num_tags)
>>> seq_length = 3  # maximum sequence length in a batch
>>> batch_size = 2  # number of samples in the batch
>>> emissions = torch.randn(seq_length, batch_size, num_tags)
>>> tags = torch.tensor([
... [0, 1], [2, 4], [3, 1]
... ], dtype=torch.long)  # (seq_length, batch_size)
>>> model(emissions, tags)

**Comment by kmkurn** [comment]
Hi, I tried on my machine and it worked just fine. What version of PyTorch are you using?

**Comment by iamxinxin** [comment]
I got the same error with pytorch==1.6.0

**Comment by kmkurn** [comment]
It works just fine for me with PyTorch 1.6.0. Are you sure your `tags` is of dtype long?

**Comment by iamxinxin** [comment]
Thanks! Float tensor found, it works aftrt I changed it to long

**Comment by kmkurn** [comment]
Great! Glad that you got it working. I'm closing this issue.
