### ISSUE TITLE
Computer Vision usage

### ISSUE THREAD

**Issue by yassouali** [kmkurn/pytorch-crf#43]
Hi, 

I was wandering if this implementation can work in a computer vision setting (semantic segmentation),  I am using this implementation (https://github.com/lucasb-eyer/pydensecrf) but it is quite slow and I would love a GPU based implementation, so if there any chance this implementation is similar to the fully connected CRF using in https://arxiv.org/abs/1210.5644 or is it only for NLP.

Thank you.

**Comment by kmkurn** [comment]
Hi,

I've had a look at the paper, and at a glance, it seems very different from the linear-chain CRF this library is intended for. So I don't think this library is similar to that. You need to modify the code quite drastically, I think.

**Comment by yassouali** [comment]
Thank you very much for checking, much appreciated, I am reading the code to see if it is feasible.

**Comment by sinahmr** [comment]
Hi,
@yassouali Could you find a workaround for this? Perhaps you implemented DenseCRF for pytorch, or found another project for that?
Thanks
