### ISSUE TITLE
Why can't I mask the first token?

### ISSUE THREAD

**Issue by wuyaoxuehun** [kmkurn/pytorch-crf#46]

**Comment by kmkurn** [comment]
To ensure the input has at least 1 token, so the start and end transition score can be computed properly. Masking the first token means the input has zero length, and my assumption is that such inputs are erroneous and should never happen. Is there a valid case where this assumption does not hold?

**Comment by wuyaoxuehun** [comment]
I'm trying to use bert with crf to so some NER tasks, and the first token is always [CLS], which is not to be classified. So I think this is a valid case. Thanks for replying.

**Comment by kmkurn** [comment]
Yes but that sequence is not empty, right? You have [CLS] then at least another token, don't you? What I would suggest is to remove the first token [CLS] before feeding it into the CRF.

**Comment by wuyaoxuehun** [comment]
Yes, that was what I  did. I think this is a little inflexible, but your code is good enough. Thanks.

**Comment by kmkurn** [comment]
I see. I'm still reluctant to implement this because I think it'll make the code a lot messier, and I'm not sure if it's worth it. Removing [CLS] seems so much easier. So I'm closing this for now.
