### ISSUE TITLE
Transition score for masked timesteps

### ISSUE THREAD

**Issue by Anshul-Gupta24** [kmkurn/pytorch-crf#53]
Hi, thanks for the great library. I was going through your code and had a doubt regarding the computation of score when a timestep is masked. Specifically, in line 192 of torch_crf/\_\_init\_\_.py:

`score += self.transitions[tags[i - 1], tags[i]] * mask[i]`

Shouldn't this be:

`score += self.transitions[tags[i - 1], tags[i]] * mask[i] * mask[i-1]`

As we do not want transition score to be calculated when the previous timestep was masked. Thanks!

**Comment by kmkurn** [comment]
Hi, thanks for checking out the library! The mask is assumed to be a length mask, so it should be ones followed by (possibly none) zeroes. So, if `mask[i-1]==0` then `mask[i]==0` as well. In this case, the two equations are equivalent.

**Comment by Anshul-Gupta24** [comment]
I see, thanks for the clarification. I currently have some masked values in between timesteps so this might affect outputs there. Could the mask be converted to a general purpose one by making the change above (although the first timestep cannot still be masked). Let me know what you think.

**Comment by kmkurn** [comment]
I guess you could, but then the transition code might get complicated since you can have arbitrary number of masked time steps between two valid (unmasked) ones. Off the top of my head, I'm not sure if there's a way to do so without changing the code drastically.
