### ISSUE TITLE
Error in _compute_score when working with a batch

### ISSUE THREAD

**Issue by reboutli-crim** [kmkurn/pytorch-crf#65]
I got an error on line 186: score = self.start_transitions[tags[0]]
The error  is
IndexError: The shape of the mask [32] at index 0 does not match the shape of the indexed tensor [21] at index 0
32 is the size of my batch and 21 the number of  tags.

**Comment by Bomme** [comment]
I hit the same error. I don't think it's a bug in the library. Here is what I did:

my `tags` had `dtype` `torch.uint8` that leads to unintended behaviour with the indexing. Once I switched the `dtype` of `tags` to `torch.long` (same as `torch.int64`), it worked.

Hope this helps!

**Comment by kmkurn** [comment]
@reboutli-crim Hi, can you confirm if the solution above works?

**Comment by reboutli-crim** [comment]
Yes, this solution works. Thanks a lot @Bomme!
