### ISSUE TITLE
ERROR: No matching distribution found for pytorch-crf

### ISSUE THREAD

**Issue by ardellelee** [kmkurn/pytorch-crf#68]
Hi, I cannot install pytorch-crf with pip. Does anyone come across the same issue?

I'm using Python3.5 virtual environment. Error message:

$ pip install pytorch-crf
ERROR: Could not find a version that satisfies the requirement pytorch-crf (from versions: none)
ERROR: No matching distribution found for pytorch-crf

**Comment by kmkurn** [comment]
The lowest supported version of Python is 3.6. Upgrading Python should solve it.
