### ISSUE TITLE
About the mask

### ISSUE THREAD

**Issue by for-just-we** [kmkurn/pytorch-crf#77]
I want to use CRF after a BERT layer with a Linear layer. But the BERT always need a `max_seq_len`. So there will be many padding value in a sequence. 

just like `max_seq_len = 10` , and input_seq = [ 0 ,1 ,2, 3, 4, 0, 0, 0, 0, 0] , mask = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0].

is `CRF.decode(input_seq, mask=mask) `right?

**Comment by kmkurn** [comment]
Yes, that seems right.

**Comment by kmkurn** [comment]
I'm assuming you got it working correctly so I'll be closing the issue.
