### ISSUE TITLE
Clarification about masks

### ISSUE THREAD

**Issue by ViktorooReps** [kmkurn/pytorch-crf#78]
Hi! Thanks for your great library! Saved me a lot of time.

I've padded RNN inputs and want to feed it's outputs to CRF. 
If I understood your `_compute_score` correctly, I need to pad tags tensor as well with some valid tags (to avoid out of bounds exception). These tags won' t affect anything, right?

**Comment by kmkurn** [comment]
Yes, it should be fine as long as you pass the correct mask. Glad you find the library useful!
